---
title: "Second Asset"
---

```{r}
library(xml2)
library(rvest)
library(tibble)
library(purrr)
library(stringr)
library(dplyr)
library(lubridate)
```

### Functions
```{r}
##### review_title function ##### 
review_title <- function(html){
  html %>%
  html_nodes(".tbl.fill.reviewHdr") %>%
  map_df(~list(title = html_nodes(.x,'.reviewer') %>% html_text() %>% {if(length(.) == 0) NA else .}))
}

##### intreview_location function ##### 
intreview_location <- function(html){
  html %>%
  html_nodes('.tbl.fill.reviewHdr') %>%
  map_df(~list(location = html_node(.x, '.authorLocation') %>% html_text() %>% {if(length(.) == 0) NA else .}))
}

##### intreview_outcome function ##### 
intreview_outcome <- function(html){
  html %>%
  html_nodes(".interviewOutcomes") %>%
  html_text()
}
```

### Inputs
```{r}
url <- "https://www.glassdoor.com/Interview/Amazon-Interview-Questions-E6036_P%d.htm"
last_page <- 1000
pages_url <- str_c(sprintf(url,1:last_page))
pages_url <- gsub("_P1.htm",".htm",pages_url)
pages_url[1]
pages_url[last_page]
```

### Analysis
```{r}
map_df(1:last_page,function(i){
  cat(".")
  page_html <- read_html (pages_url[i])
  Title <- review_title (page_html)
  Location <- intreview_location (page_html)
  Outcome <- intreview_outcome (page_html)
    Offer_outcome <- str_extract (Outcome,"Accepted|No")
    Experience_outcome <- str_extract (Outcome,"Positive|Negative")
    Interview_outcome <- str_extract (Outcome,"Difficult|Easy|Average")
  data.frame(Title,Location,Offer_outcome,Experience_outcome,Interview_outcome,stringsAsFactors = FALSE)
}) -> result
```

### Number of interview experience (Negative/Positive) in the top 10 Amazon's offices
```{r}
y <- table(result$location, result$Experience_outcome)
y <- tail(y[order(rowSums(y)),],n=10)
y <- t(y)
par(mar=c(12,4,1,0.1))
barplot(y, col = 2:3, legend = c("Negative", "Positive"), args.legend = list(x ='top'), ylab = "Counts", cex.axis=0.8, cex.name=0.8, las=2, lwd=2, beside=TRUE)
```

### Number of Accepted/Rejected interview in the top 10 Amazon's offices
```{r}
y <- table(result$location, result$Offer_outcome)
y <- tail(y[order(rowSums(y)),],n=10)
y <- t(y)
par(mar=c(12,4,1,0.1))
barplot(y, col = 3:2, legend = c("Accepted","Rejected"), args.legend = list(x ='top'), ylab = "Counts", cex.axis=0.8, cex.name=0.8, las=2, lwd=2, beside=TRUE)
```

### Number of Interview Hardship Level (Easy/Average/Hard) in the top 10 top job openings in Amazon
```{r}
y <- table(result$title, result$Interview_outcome)
y <- tail(y[order(rowSums(y)),],n=10)
y <- t(y)
par(mar=c(12,4,1,0.1))
barplot(y, col = c("blue","red","green"), legend = c("Average", "Difficult", "Easy"), args.legend = list(x ='top'), ylab = "Counts", cex.axis=0.8, cex.name=0.8, las=2, lwd=2, beside=TRUE)
```